// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Zeet.Model.Inputs
{

    public sealed class CreateAppResourcesInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("cpu", required: true)]
        public Input<double> Cpu { get; set; } = null!;

        [Input("ephemeralStorage")]
        public Input<double>? EphemeralStorage { get; set; }

        [Input("memory", required: true)]
        public Input<string> Memory { get; set; } = null!;

        [Input("spotInstance")]
        public Input<bool>? SpotInstance { get; set; }

        public CreateAppResourcesInputArgs()
        {
        }
        public static new CreateAppResourcesInputArgs Empty => new CreateAppResourcesInputArgs();
    }
}
