// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ZeetNative.Model.Inputs
{

    public sealed class CreateAppEnvironmentVariableInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("sealed")]
        public Input<bool>? Sealed { get; set; }

        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public CreateAppEnvironmentVariableInputArgs()
        {
        }
        public static new CreateAppEnvironmentVariableInputArgs Empty => new CreateAppEnvironmentVariableInputArgs();
    }
}
