// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ZeetNative.Model.Inputs
{

    public sealed class CreateAppGithubInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("productionBranch", required: true)]
        public Input<string> ProductionBranch { get; set; } = null!;

        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public CreateAppGithubInputArgs()
        {
        }
        public static new CreateAppGithubInputArgs Empty => new CreateAppGithubInputArgs();
    }
}
