// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ZeetNative.Model.Inputs
{

    public sealed class CreateAppDeployInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("clusterId")]
        public Input<string>? ClusterId { get; set; }

        [Input("deployTarget", required: true)]
        public Input<string> DeployTarget { get; set; } = null!;

        public CreateAppDeployInputArgs()
        {
        }
        public static new CreateAppDeployInputArgs Empty => new CreateAppDeployInputArgs();
    }
}
