// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Zeet.Model.Inputs
{

    public sealed class CreateAppDockerInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("dockerImage", required: true)]
        public Input<string> DockerImage { get; set; } = null!;

        public CreateAppDockerInputArgs()
        {
        }
        public static new CreateAppDockerInputArgs Empty => new CreateAppDockerInputArgs();
    }
}
