// Code generated by pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package model

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type CreateAppBuildInput struct {
	DockerfilePath *string `pulumi:"dockerfilePath"`
	Type           string  `pulumi:"type"`
}

// CreateAppBuildInputInput is an input type that accepts CreateAppBuildInputArgs and CreateAppBuildInputOutput values.
// You can construct a concrete instance of `CreateAppBuildInputInput` via:
//
//	CreateAppBuildInputArgs{...}
type CreateAppBuildInputInput interface {
	pulumi.Input

	ToCreateAppBuildInputOutput() CreateAppBuildInputOutput
	ToCreateAppBuildInputOutputWithContext(context.Context) CreateAppBuildInputOutput
}

type CreateAppBuildInputArgs struct {
	DockerfilePath pulumi.StringPtrInput `pulumi:"dockerfilePath"`
	Type           pulumi.StringInput    `pulumi:"type"`
}

func (CreateAppBuildInputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*CreateAppBuildInput)(nil)).Elem()
}

func (i CreateAppBuildInputArgs) ToCreateAppBuildInputOutput() CreateAppBuildInputOutput {
	return i.ToCreateAppBuildInputOutputWithContext(context.Background())
}

func (i CreateAppBuildInputArgs) ToCreateAppBuildInputOutputWithContext(ctx context.Context) CreateAppBuildInputOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CreateAppBuildInputOutput)
}

func (i CreateAppBuildInputArgs) ToCreateAppBuildInputPtrOutput() CreateAppBuildInputPtrOutput {
	return i.ToCreateAppBuildInputPtrOutputWithContext(context.Background())
}

func (i CreateAppBuildInputArgs) ToCreateAppBuildInputPtrOutputWithContext(ctx context.Context) CreateAppBuildInputPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CreateAppBuildInputOutput).ToCreateAppBuildInputPtrOutputWithContext(ctx)
}

// CreateAppBuildInputPtrInput is an input type that accepts CreateAppBuildInputArgs, CreateAppBuildInputPtr and CreateAppBuildInputPtrOutput values.
// You can construct a concrete instance of `CreateAppBuildInputPtrInput` via:
//
//	        CreateAppBuildInputArgs{...}
//
//	or:
//
//	        nil
type CreateAppBuildInputPtrInput interface {
	pulumi.Input

	ToCreateAppBuildInputPtrOutput() CreateAppBuildInputPtrOutput
	ToCreateAppBuildInputPtrOutputWithContext(context.Context) CreateAppBuildInputPtrOutput
}

type createAppBuildInputPtrType CreateAppBuildInputArgs

func CreateAppBuildInputPtr(v *CreateAppBuildInputArgs) CreateAppBuildInputPtrInput {
	return (*createAppBuildInputPtrType)(v)
}

func (*createAppBuildInputPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**CreateAppBuildInput)(nil)).Elem()
}

func (i *createAppBuildInputPtrType) ToCreateAppBuildInputPtrOutput() CreateAppBuildInputPtrOutput {
	return i.ToCreateAppBuildInputPtrOutputWithContext(context.Background())
}

func (i *createAppBuildInputPtrType) ToCreateAppBuildInputPtrOutputWithContext(ctx context.Context) CreateAppBuildInputPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CreateAppBuildInputPtrOutput)
}

type CreateAppBuildInputOutput struct{ *pulumi.OutputState }

func (CreateAppBuildInputOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CreateAppBuildInput)(nil)).Elem()
}

func (o CreateAppBuildInputOutput) ToCreateAppBuildInputOutput() CreateAppBuildInputOutput {
	return o
}

func (o CreateAppBuildInputOutput) ToCreateAppBuildInputOutputWithContext(ctx context.Context) CreateAppBuildInputOutput {
	return o
}

func (o CreateAppBuildInputOutput) ToCreateAppBuildInputPtrOutput() CreateAppBuildInputPtrOutput {
	return o.ToCreateAppBuildInputPtrOutputWithContext(context.Background())
}

func (o CreateAppBuildInputOutput) ToCreateAppBuildInputPtrOutputWithContext(ctx context.Context) CreateAppBuildInputPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v CreateAppBuildInput) *CreateAppBuildInput {
		return &v
	}).(CreateAppBuildInputPtrOutput)
}

func (o CreateAppBuildInputOutput) DockerfilePath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v CreateAppBuildInput) *string { return v.DockerfilePath }).(pulumi.StringPtrOutput)
}

func (o CreateAppBuildInputOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v CreateAppBuildInput) string { return v.Type }).(pulumi.StringOutput)
}

type CreateAppBuildInputPtrOutput struct{ *pulumi.OutputState }

func (CreateAppBuildInputPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CreateAppBuildInput)(nil)).Elem()
}

func (o CreateAppBuildInputPtrOutput) ToCreateAppBuildInputPtrOutput() CreateAppBuildInputPtrOutput {
	return o
}

func (o CreateAppBuildInputPtrOutput) ToCreateAppBuildInputPtrOutputWithContext(ctx context.Context) CreateAppBuildInputPtrOutput {
	return o
}

func (o CreateAppBuildInputPtrOutput) Elem() CreateAppBuildInputOutput {
	return o.ApplyT(func(v *CreateAppBuildInput) CreateAppBuildInput {
		if v != nil {
			return *v
		}
		var ret CreateAppBuildInput
		return ret
	}).(CreateAppBuildInputOutput)
}

func (o CreateAppBuildInputPtrOutput) DockerfilePath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CreateAppBuildInput) *string {
		if v == nil {
			return nil
		}
		return v.DockerfilePath
	}).(pulumi.StringPtrOutput)
}

func (o CreateAppBuildInputPtrOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CreateAppBuildInput) *string {
		if v == nil {
			return nil
		}
		return &v.Type
	}).(pulumi.StringPtrOutput)
}

type CreateAppDeployInput struct {
	ClusterId    *string `pulumi:"clusterId"`
	DeployTarget string  `pulumi:"deployTarget"`
}

// CreateAppDeployInputInput is an input type that accepts CreateAppDeployInputArgs and CreateAppDeployInputOutput values.
// You can construct a concrete instance of `CreateAppDeployInputInput` via:
//
//	CreateAppDeployInputArgs{...}
type CreateAppDeployInputInput interface {
	pulumi.Input

	ToCreateAppDeployInputOutput() CreateAppDeployInputOutput
	ToCreateAppDeployInputOutputWithContext(context.Context) CreateAppDeployInputOutput
}

type CreateAppDeployInputArgs struct {
	ClusterId    pulumi.StringPtrInput `pulumi:"clusterId"`
	DeployTarget pulumi.StringInput    `pulumi:"deployTarget"`
}

func (CreateAppDeployInputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*CreateAppDeployInput)(nil)).Elem()
}

func (i CreateAppDeployInputArgs) ToCreateAppDeployInputOutput() CreateAppDeployInputOutput {
	return i.ToCreateAppDeployInputOutputWithContext(context.Background())
}

func (i CreateAppDeployInputArgs) ToCreateAppDeployInputOutputWithContext(ctx context.Context) CreateAppDeployInputOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CreateAppDeployInputOutput)
}

type CreateAppDeployInputOutput struct{ *pulumi.OutputState }

func (CreateAppDeployInputOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CreateAppDeployInput)(nil)).Elem()
}

func (o CreateAppDeployInputOutput) ToCreateAppDeployInputOutput() CreateAppDeployInputOutput {
	return o
}

func (o CreateAppDeployInputOutput) ToCreateAppDeployInputOutputWithContext(ctx context.Context) CreateAppDeployInputOutput {
	return o
}

func (o CreateAppDeployInputOutput) ClusterId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v CreateAppDeployInput) *string { return v.ClusterId }).(pulumi.StringPtrOutput)
}

func (o CreateAppDeployInputOutput) DeployTarget() pulumi.StringOutput {
	return o.ApplyT(func(v CreateAppDeployInput) string { return v.DeployTarget }).(pulumi.StringOutput)
}

type CreateAppDockerInput struct {
	DockerImage string `pulumi:"dockerImage"`
}

// CreateAppDockerInputInput is an input type that accepts CreateAppDockerInputArgs and CreateAppDockerInputOutput values.
// You can construct a concrete instance of `CreateAppDockerInputInput` via:
//
//	CreateAppDockerInputArgs{...}
type CreateAppDockerInputInput interface {
	pulumi.Input

	ToCreateAppDockerInputOutput() CreateAppDockerInputOutput
	ToCreateAppDockerInputOutputWithContext(context.Context) CreateAppDockerInputOutput
}

type CreateAppDockerInputArgs struct {
	DockerImage pulumi.StringInput `pulumi:"dockerImage"`
}

func (CreateAppDockerInputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*CreateAppDockerInput)(nil)).Elem()
}

func (i CreateAppDockerInputArgs) ToCreateAppDockerInputOutput() CreateAppDockerInputOutput {
	return i.ToCreateAppDockerInputOutputWithContext(context.Background())
}

func (i CreateAppDockerInputArgs) ToCreateAppDockerInputOutputWithContext(ctx context.Context) CreateAppDockerInputOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CreateAppDockerInputOutput)
}

func (i CreateAppDockerInputArgs) ToCreateAppDockerInputPtrOutput() CreateAppDockerInputPtrOutput {
	return i.ToCreateAppDockerInputPtrOutputWithContext(context.Background())
}

func (i CreateAppDockerInputArgs) ToCreateAppDockerInputPtrOutputWithContext(ctx context.Context) CreateAppDockerInputPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CreateAppDockerInputOutput).ToCreateAppDockerInputPtrOutputWithContext(ctx)
}

// CreateAppDockerInputPtrInput is an input type that accepts CreateAppDockerInputArgs, CreateAppDockerInputPtr and CreateAppDockerInputPtrOutput values.
// You can construct a concrete instance of `CreateAppDockerInputPtrInput` via:
//
//	        CreateAppDockerInputArgs{...}
//
//	or:
//
//	        nil
type CreateAppDockerInputPtrInput interface {
	pulumi.Input

	ToCreateAppDockerInputPtrOutput() CreateAppDockerInputPtrOutput
	ToCreateAppDockerInputPtrOutputWithContext(context.Context) CreateAppDockerInputPtrOutput
}

type createAppDockerInputPtrType CreateAppDockerInputArgs

func CreateAppDockerInputPtr(v *CreateAppDockerInputArgs) CreateAppDockerInputPtrInput {
	return (*createAppDockerInputPtrType)(v)
}

func (*createAppDockerInputPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**CreateAppDockerInput)(nil)).Elem()
}

func (i *createAppDockerInputPtrType) ToCreateAppDockerInputPtrOutput() CreateAppDockerInputPtrOutput {
	return i.ToCreateAppDockerInputPtrOutputWithContext(context.Background())
}

func (i *createAppDockerInputPtrType) ToCreateAppDockerInputPtrOutputWithContext(ctx context.Context) CreateAppDockerInputPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CreateAppDockerInputPtrOutput)
}

type CreateAppDockerInputOutput struct{ *pulumi.OutputState }

func (CreateAppDockerInputOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CreateAppDockerInput)(nil)).Elem()
}

func (o CreateAppDockerInputOutput) ToCreateAppDockerInputOutput() CreateAppDockerInputOutput {
	return o
}

func (o CreateAppDockerInputOutput) ToCreateAppDockerInputOutputWithContext(ctx context.Context) CreateAppDockerInputOutput {
	return o
}

func (o CreateAppDockerInputOutput) ToCreateAppDockerInputPtrOutput() CreateAppDockerInputPtrOutput {
	return o.ToCreateAppDockerInputPtrOutputWithContext(context.Background())
}

func (o CreateAppDockerInputOutput) ToCreateAppDockerInputPtrOutputWithContext(ctx context.Context) CreateAppDockerInputPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v CreateAppDockerInput) *CreateAppDockerInput {
		return &v
	}).(CreateAppDockerInputPtrOutput)
}

func (o CreateAppDockerInputOutput) DockerImage() pulumi.StringOutput {
	return o.ApplyT(func(v CreateAppDockerInput) string { return v.DockerImage }).(pulumi.StringOutput)
}

type CreateAppDockerInputPtrOutput struct{ *pulumi.OutputState }

func (CreateAppDockerInputPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CreateAppDockerInput)(nil)).Elem()
}

func (o CreateAppDockerInputPtrOutput) ToCreateAppDockerInputPtrOutput() CreateAppDockerInputPtrOutput {
	return o
}

func (o CreateAppDockerInputPtrOutput) ToCreateAppDockerInputPtrOutputWithContext(ctx context.Context) CreateAppDockerInputPtrOutput {
	return o
}

func (o CreateAppDockerInputPtrOutput) Elem() CreateAppDockerInputOutput {
	return o.ApplyT(func(v *CreateAppDockerInput) CreateAppDockerInput {
		if v != nil {
			return *v
		}
		var ret CreateAppDockerInput
		return ret
	}).(CreateAppDockerInputOutput)
}

func (o CreateAppDockerInputPtrOutput) DockerImage() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CreateAppDockerInput) *string {
		if v == nil {
			return nil
		}
		return &v.DockerImage
	}).(pulumi.StringPtrOutput)
}

type CreateAppEnvironmentVariableInput struct {
	Name   string `pulumi:"name"`
	Sealed *bool  `pulumi:"sealed"`
	Value  string `pulumi:"value"`
}

// CreateAppEnvironmentVariableInputInput is an input type that accepts CreateAppEnvironmentVariableInputArgs and CreateAppEnvironmentVariableInputOutput values.
// You can construct a concrete instance of `CreateAppEnvironmentVariableInputInput` via:
//
//	CreateAppEnvironmentVariableInputArgs{...}
type CreateAppEnvironmentVariableInputInput interface {
	pulumi.Input

	ToCreateAppEnvironmentVariableInputOutput() CreateAppEnvironmentVariableInputOutput
	ToCreateAppEnvironmentVariableInputOutputWithContext(context.Context) CreateAppEnvironmentVariableInputOutput
}

type CreateAppEnvironmentVariableInputArgs struct {
	Name   pulumi.StringInput  `pulumi:"name"`
	Sealed pulumi.BoolPtrInput `pulumi:"sealed"`
	Value  pulumi.StringInput  `pulumi:"value"`
}

func (CreateAppEnvironmentVariableInputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*CreateAppEnvironmentVariableInput)(nil)).Elem()
}

func (i CreateAppEnvironmentVariableInputArgs) ToCreateAppEnvironmentVariableInputOutput() CreateAppEnvironmentVariableInputOutput {
	return i.ToCreateAppEnvironmentVariableInputOutputWithContext(context.Background())
}

func (i CreateAppEnvironmentVariableInputArgs) ToCreateAppEnvironmentVariableInputOutputWithContext(ctx context.Context) CreateAppEnvironmentVariableInputOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CreateAppEnvironmentVariableInputOutput)
}

// CreateAppEnvironmentVariableInputArrayInput is an input type that accepts CreateAppEnvironmentVariableInputArray and CreateAppEnvironmentVariableInputArrayOutput values.
// You can construct a concrete instance of `CreateAppEnvironmentVariableInputArrayInput` via:
//
//	CreateAppEnvironmentVariableInputArray{ CreateAppEnvironmentVariableInputArgs{...} }
type CreateAppEnvironmentVariableInputArrayInput interface {
	pulumi.Input

	ToCreateAppEnvironmentVariableInputArrayOutput() CreateAppEnvironmentVariableInputArrayOutput
	ToCreateAppEnvironmentVariableInputArrayOutputWithContext(context.Context) CreateAppEnvironmentVariableInputArrayOutput
}

type CreateAppEnvironmentVariableInputArray []CreateAppEnvironmentVariableInputInput

func (CreateAppEnvironmentVariableInputArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]CreateAppEnvironmentVariableInput)(nil)).Elem()
}

func (i CreateAppEnvironmentVariableInputArray) ToCreateAppEnvironmentVariableInputArrayOutput() CreateAppEnvironmentVariableInputArrayOutput {
	return i.ToCreateAppEnvironmentVariableInputArrayOutputWithContext(context.Background())
}

func (i CreateAppEnvironmentVariableInputArray) ToCreateAppEnvironmentVariableInputArrayOutputWithContext(ctx context.Context) CreateAppEnvironmentVariableInputArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CreateAppEnvironmentVariableInputArrayOutput)
}

type CreateAppEnvironmentVariableInputOutput struct{ *pulumi.OutputState }

func (CreateAppEnvironmentVariableInputOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CreateAppEnvironmentVariableInput)(nil)).Elem()
}

func (o CreateAppEnvironmentVariableInputOutput) ToCreateAppEnvironmentVariableInputOutput() CreateAppEnvironmentVariableInputOutput {
	return o
}

func (o CreateAppEnvironmentVariableInputOutput) ToCreateAppEnvironmentVariableInputOutputWithContext(ctx context.Context) CreateAppEnvironmentVariableInputOutput {
	return o
}

func (o CreateAppEnvironmentVariableInputOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v CreateAppEnvironmentVariableInput) string { return v.Name }).(pulumi.StringOutput)
}

func (o CreateAppEnvironmentVariableInputOutput) Sealed() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v CreateAppEnvironmentVariableInput) *bool { return v.Sealed }).(pulumi.BoolPtrOutput)
}

func (o CreateAppEnvironmentVariableInputOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v CreateAppEnvironmentVariableInput) string { return v.Value }).(pulumi.StringOutput)
}

type CreateAppEnvironmentVariableInputArrayOutput struct{ *pulumi.OutputState }

func (CreateAppEnvironmentVariableInputArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]CreateAppEnvironmentVariableInput)(nil)).Elem()
}

func (o CreateAppEnvironmentVariableInputArrayOutput) ToCreateAppEnvironmentVariableInputArrayOutput() CreateAppEnvironmentVariableInputArrayOutput {
	return o
}

func (o CreateAppEnvironmentVariableInputArrayOutput) ToCreateAppEnvironmentVariableInputArrayOutputWithContext(ctx context.Context) CreateAppEnvironmentVariableInputArrayOutput {
	return o
}

func (o CreateAppEnvironmentVariableInputArrayOutput) Index(i pulumi.IntInput) CreateAppEnvironmentVariableInputOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) CreateAppEnvironmentVariableInput {
		return vs[0].([]CreateAppEnvironmentVariableInput)[vs[1].(int)]
	}).(CreateAppEnvironmentVariableInputOutput)
}

type CreateAppGithubInput struct {
	ProductionBranch string `pulumi:"productionBranch"`
	Url              string `pulumi:"url"`
}

// CreateAppGithubInputInput is an input type that accepts CreateAppGithubInputArgs and CreateAppGithubInputOutput values.
// You can construct a concrete instance of `CreateAppGithubInputInput` via:
//
//	CreateAppGithubInputArgs{...}
type CreateAppGithubInputInput interface {
	pulumi.Input

	ToCreateAppGithubInputOutput() CreateAppGithubInputOutput
	ToCreateAppGithubInputOutputWithContext(context.Context) CreateAppGithubInputOutput
}

type CreateAppGithubInputArgs struct {
	ProductionBranch pulumi.StringInput `pulumi:"productionBranch"`
	Url              pulumi.StringInput `pulumi:"url"`
}

func (CreateAppGithubInputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*CreateAppGithubInput)(nil)).Elem()
}

func (i CreateAppGithubInputArgs) ToCreateAppGithubInputOutput() CreateAppGithubInputOutput {
	return i.ToCreateAppGithubInputOutputWithContext(context.Background())
}

func (i CreateAppGithubInputArgs) ToCreateAppGithubInputOutputWithContext(ctx context.Context) CreateAppGithubInputOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CreateAppGithubInputOutput)
}

func (i CreateAppGithubInputArgs) ToCreateAppGithubInputPtrOutput() CreateAppGithubInputPtrOutput {
	return i.ToCreateAppGithubInputPtrOutputWithContext(context.Background())
}

func (i CreateAppGithubInputArgs) ToCreateAppGithubInputPtrOutputWithContext(ctx context.Context) CreateAppGithubInputPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CreateAppGithubInputOutput).ToCreateAppGithubInputPtrOutputWithContext(ctx)
}

// CreateAppGithubInputPtrInput is an input type that accepts CreateAppGithubInputArgs, CreateAppGithubInputPtr and CreateAppGithubInputPtrOutput values.
// You can construct a concrete instance of `CreateAppGithubInputPtrInput` via:
//
//	        CreateAppGithubInputArgs{...}
//
//	or:
//
//	        nil
type CreateAppGithubInputPtrInput interface {
	pulumi.Input

	ToCreateAppGithubInputPtrOutput() CreateAppGithubInputPtrOutput
	ToCreateAppGithubInputPtrOutputWithContext(context.Context) CreateAppGithubInputPtrOutput
}

type createAppGithubInputPtrType CreateAppGithubInputArgs

func CreateAppGithubInputPtr(v *CreateAppGithubInputArgs) CreateAppGithubInputPtrInput {
	return (*createAppGithubInputPtrType)(v)
}

func (*createAppGithubInputPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**CreateAppGithubInput)(nil)).Elem()
}

func (i *createAppGithubInputPtrType) ToCreateAppGithubInputPtrOutput() CreateAppGithubInputPtrOutput {
	return i.ToCreateAppGithubInputPtrOutputWithContext(context.Background())
}

func (i *createAppGithubInputPtrType) ToCreateAppGithubInputPtrOutputWithContext(ctx context.Context) CreateAppGithubInputPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CreateAppGithubInputPtrOutput)
}

type CreateAppGithubInputOutput struct{ *pulumi.OutputState }

func (CreateAppGithubInputOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CreateAppGithubInput)(nil)).Elem()
}

func (o CreateAppGithubInputOutput) ToCreateAppGithubInputOutput() CreateAppGithubInputOutput {
	return o
}

func (o CreateAppGithubInputOutput) ToCreateAppGithubInputOutputWithContext(ctx context.Context) CreateAppGithubInputOutput {
	return o
}

func (o CreateAppGithubInputOutput) ToCreateAppGithubInputPtrOutput() CreateAppGithubInputPtrOutput {
	return o.ToCreateAppGithubInputPtrOutputWithContext(context.Background())
}

func (o CreateAppGithubInputOutput) ToCreateAppGithubInputPtrOutputWithContext(ctx context.Context) CreateAppGithubInputPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v CreateAppGithubInput) *CreateAppGithubInput {
		return &v
	}).(CreateAppGithubInputPtrOutput)
}

func (o CreateAppGithubInputOutput) ProductionBranch() pulumi.StringOutput {
	return o.ApplyT(func(v CreateAppGithubInput) string { return v.ProductionBranch }).(pulumi.StringOutput)
}

func (o CreateAppGithubInputOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v CreateAppGithubInput) string { return v.Url }).(pulumi.StringOutput)
}

type CreateAppGithubInputPtrOutput struct{ *pulumi.OutputState }

func (CreateAppGithubInputPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CreateAppGithubInput)(nil)).Elem()
}

func (o CreateAppGithubInputPtrOutput) ToCreateAppGithubInputPtrOutput() CreateAppGithubInputPtrOutput {
	return o
}

func (o CreateAppGithubInputPtrOutput) ToCreateAppGithubInputPtrOutputWithContext(ctx context.Context) CreateAppGithubInputPtrOutput {
	return o
}

func (o CreateAppGithubInputPtrOutput) Elem() CreateAppGithubInputOutput {
	return o.ApplyT(func(v *CreateAppGithubInput) CreateAppGithubInput {
		if v != nil {
			return *v
		}
		var ret CreateAppGithubInput
		return ret
	}).(CreateAppGithubInputOutput)
}

func (o CreateAppGithubInputPtrOutput) ProductionBranch() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CreateAppGithubInput) *string {
		if v == nil {
			return nil
		}
		return &v.ProductionBranch
	}).(pulumi.StringPtrOutput)
}

func (o CreateAppGithubInputPtrOutput) Url() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CreateAppGithubInput) *string {
		if v == nil {
			return nil
		}
		return &v.Url
	}).(pulumi.StringPtrOutput)
}

type CreateAppResourcesInput struct {
	Cpu              float64 `pulumi:"cpu"`
	EphemeralStorage float64 `pulumi:"ephemeralStorage"`
	Memory           string  `pulumi:"memory"`
	SpotInstance     bool    `pulumi:"spotInstance"`
}

// CreateAppResourcesInputInput is an input type that accepts CreateAppResourcesInputArgs and CreateAppResourcesInputOutput values.
// You can construct a concrete instance of `CreateAppResourcesInputInput` via:
//
//	CreateAppResourcesInputArgs{...}
type CreateAppResourcesInputInput interface {
	pulumi.Input

	ToCreateAppResourcesInputOutput() CreateAppResourcesInputOutput
	ToCreateAppResourcesInputOutputWithContext(context.Context) CreateAppResourcesInputOutput
}

type CreateAppResourcesInputArgs struct {
	Cpu              pulumi.Float64Input `pulumi:"cpu"`
	EphemeralStorage pulumi.Float64Input `pulumi:"ephemeralStorage"`
	Memory           pulumi.StringInput  `pulumi:"memory"`
	SpotInstance     pulumi.BoolInput    `pulumi:"spotInstance"`
}

func (CreateAppResourcesInputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*CreateAppResourcesInput)(nil)).Elem()
}

func (i CreateAppResourcesInputArgs) ToCreateAppResourcesInputOutput() CreateAppResourcesInputOutput {
	return i.ToCreateAppResourcesInputOutputWithContext(context.Background())
}

func (i CreateAppResourcesInputArgs) ToCreateAppResourcesInputOutputWithContext(ctx context.Context) CreateAppResourcesInputOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CreateAppResourcesInputOutput)
}

type CreateAppResourcesInputOutput struct{ *pulumi.OutputState }

func (CreateAppResourcesInputOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CreateAppResourcesInput)(nil)).Elem()
}

func (o CreateAppResourcesInputOutput) ToCreateAppResourcesInputOutput() CreateAppResourcesInputOutput {
	return o
}

func (o CreateAppResourcesInputOutput) ToCreateAppResourcesInputOutputWithContext(ctx context.Context) CreateAppResourcesInputOutput {
	return o
}

func (o CreateAppResourcesInputOutput) Cpu() pulumi.Float64Output {
	return o.ApplyT(func(v CreateAppResourcesInput) float64 { return v.Cpu }).(pulumi.Float64Output)
}

func (o CreateAppResourcesInputOutput) EphemeralStorage() pulumi.Float64Output {
	return o.ApplyT(func(v CreateAppResourcesInput) float64 { return v.EphemeralStorage }).(pulumi.Float64Output)
}

func (o CreateAppResourcesInputOutput) Memory() pulumi.StringOutput {
	return o.ApplyT(func(v CreateAppResourcesInput) string { return v.Memory }).(pulumi.StringOutput)
}

func (o CreateAppResourcesInputOutput) SpotInstance() pulumi.BoolOutput {
	return o.ApplyT(func(v CreateAppResourcesInput) bool { return v.SpotInstance }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CreateAppBuildInputInput)(nil)).Elem(), CreateAppBuildInputArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*CreateAppBuildInputPtrInput)(nil)).Elem(), CreateAppBuildInputArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*CreateAppDeployInputInput)(nil)).Elem(), CreateAppDeployInputArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*CreateAppDockerInputInput)(nil)).Elem(), CreateAppDockerInputArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*CreateAppDockerInputPtrInput)(nil)).Elem(), CreateAppDockerInputArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*CreateAppEnvironmentVariableInputInput)(nil)).Elem(), CreateAppEnvironmentVariableInputArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*CreateAppEnvironmentVariableInputArrayInput)(nil)).Elem(), CreateAppEnvironmentVariableInputArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CreateAppGithubInputInput)(nil)).Elem(), CreateAppGithubInputArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*CreateAppGithubInputPtrInput)(nil)).Elem(), CreateAppGithubInputArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*CreateAppResourcesInputInput)(nil)).Elem(), CreateAppResourcesInputArgs{})
	pulumi.RegisterOutputType(CreateAppBuildInputOutput{})
	pulumi.RegisterOutputType(CreateAppBuildInputPtrOutput{})
	pulumi.RegisterOutputType(CreateAppDeployInputOutput{})
	pulumi.RegisterOutputType(CreateAppDockerInputOutput{})
	pulumi.RegisterOutputType(CreateAppDockerInputPtrOutput{})
	pulumi.RegisterOutputType(CreateAppEnvironmentVariableInputOutput{})
	pulumi.RegisterOutputType(CreateAppEnvironmentVariableInputArrayOutput{})
	pulumi.RegisterOutputType(CreateAppGithubInputOutput{})
	pulumi.RegisterOutputType(CreateAppGithubInputPtrOutput{})
	pulumi.RegisterOutputType(CreateAppResourcesInputOutput{})
}
