archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
#before:
#  hooks:
#    - make gen
builds:
  - binary: pulumi-resource-zeet-native
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/zeet-dev/pulumi-zeet-native/provider/cmd/pulumi-resource-zeet-native/main.Version={{.Tag }}
    main: ./cmd/pulumi-resource-zeet-native/
changelog:
  skip: true
release:
  disable: false
  prerelease: auto
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
