# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .app import *
from .environment import *
from .project import *
from .provider import *
from .random import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_zeet_native.model as __model
    model = __model
    import pulumi_zeet_native.time as __time
    time = __time
else:
    model = _utilities.lazy_import('pulumi_zeet_native.model')
    time = _utilities.lazy_import('pulumi_zeet_native.time')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "zeet-native",
  "mod": "index",
  "fqn": "pulumi_zeet_native",
  "classes": {
   "zeet-native:index:App": "App",
   "zeet-native:index:Environment": "Environment",
   "zeet-native:index:Project": "Project",
   "zeet-native:index:Random": "Random"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "zeet-native",
  "token": "pulumi:providers:zeet-native",
  "fqn": "pulumi_zeet_native",
  "class": "Provider"
 }
]
"""
)
