// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ZeetNative.Model.Outputs
{

    [OutputType]
    public sealed class CreateAppEnvironmentVariableInput
    {
        public readonly string Name;
        public readonly bool? Sealed;
        public readonly string Value;

        [OutputConstructor]
        private CreateAppEnvironmentVariableInput(
            string name,

            bool? @sealed,

            string value)
        {
            Name = name;
            Sealed = @sealed;
            Value = value;
        }
    }
}
