// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ZeetNative.Model.Outputs
{

    [OutputType]
    public sealed class CreateAppBuildInput
    {
        public readonly string? DockerfilePath;
        public readonly string Type;

        [OutputConstructor]
        private CreateAppBuildInput(
            string? dockerfilePath,

            string type)
        {
            DockerfilePath = dockerfilePath;
            Type = type;
        }
    }
}
