// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ZeetNative.Model.Outputs
{

    [OutputType]
    public sealed class CreateAppResourcesInput
    {
        public readonly double Cpu;
        public readonly double EphemeralStorage;
        public readonly string Memory;
        public readonly bool SpotInstance;

        [OutputConstructor]
        private CreateAppResourcesInput(
            double cpu,

            double ephemeralStorage,

            string memory,

            bool spotInstance)
        {
            Cpu = cpu;
            EphemeralStorage = ephemeralStorage;
            Memory = memory;
            SpotInstance = spotInstance;
        }
    }
}
