// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ZeetNative.Model.Outputs
{

    [OutputType]
    public sealed class CreateAppDockerInput
    {
        public readonly string DockerImage;

        [OutputConstructor]
        private CreateAppDockerInput(string dockerImage)
        {
            DockerImage = dockerImage;
        }
    }
}
