// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ZeetNative.Model.Outputs
{

    [OutputType]
    public sealed class CreateAppResourcesInput
    {
        public readonly string Cpu;
        public readonly string Memory;

        [OutputConstructor]
        private CreateAppResourcesInput(
            string cpu,

            string memory)
        {
            Cpu = cpu;
            Memory = memory;
        }
    }
}
